### ISSUE TITLE
"ModuleNotFoundError: No module named 'mmengine'" when running the 5.1 cell

### ISSUE THREAD

**Issue by stureremielle** [TheSkinnyRat/anime_screenshot_pipeline_colab#5]
I fulfilled all the requirements, I ran through all the required cells with no problem until the 5.1 cell. It generated this

`/usr/local/lib/python3.9/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details. warnings.warn( Traceback (most recent call last): File "/content/anime_screenshot_pipeline/detect_faces.py", line 10, in <module> from anime_face_detector import create_detector File "/usr/local/lib/python3.9/dist-packages/anime_face_detector/__init__.py", line 5, in <module> from .detector import LandmarkDetector File "/usr/local/lib/python3.9/dist-packages/anime_face_detector/detector.py", line 11, in <module> from mmdet.apis import inference_detector, init_detector File "/usr/local/lib/python3.9/dist-packages/mmdet/__init__.py", line 3, in <module> import mmengine ModuleNotFoundError: No module named 'mmengine'`

and then I proceed to install the mmengine through pip

I run the cell again to meet another problem, this time it's the mmcv

`/usr/local/lib/python3.9/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
warnings.warn(
Traceback (most recent call last):
File "/content/anime_screenshot_pipeline/detect_faces.py", line 10, in <module>
from anime_face_detector import create_detector
File "/usr/local/lib/python3.9/dist-packages/anime_face_detector/__init__.py", line 5, in <module>
from .detector import LandmarkDetector
File "/usr/local/lib/python3.9/dist-packages/anime_face_detector/detector.py", line 11, in <module>
from mmdet.apis import inference_detector, init_detector
File "/usr/local/lib/python3.9/dist-packages/mmdet/__init__.py", line 16, in <module>
assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.7.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.`

I tried to install the latest mmcv, and another problem came up

`/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Successfully installed mmcv-2.0.0
Traceback (most recent call last):
  File "/content/anime_screenshot_pipeline/detect_faces.py", line 10, in <module>
    from anime_face_detector import create_detector
  File "/usr/local/lib/python3.9/dist-packages/anime_face_detector/__init__.py", line 5, in <module>
    from .detector import LandmarkDetector
  File "/usr/local/lib/python3.9/dist-packages/anime_face_detector/detector.py", line 12, in <module>
    from mmpose.apis import inference_top_down_pose_model, init_pose_model
ImportError: cannot import name 'inference_top_down_pose_model' from 'mmpose.apis' (/usr/local/lib/python3.9/dist-packages/mmpose/apis/__init__.py)`

I honestly had no idea what to do at this point. I think I've done enough tinkering for someone who had small, smooth brain, and no coding experience

**Comment by TheSkinnyRat** [comment]
Since [hysts/anime-face-detector](https://github.com/hysts/anime-face-detector) repo has not been maintained and updated since Aug 5, 2022, there is a lot of update for their requirements and google colab itself.

I have fixed and tested it at the last commit by downgrading the torch and maintaining the [hysts/anime-face-detector](https://github.com/hysts/anime-face-detector) requirements with the fixed worked version.
